question_repo/apps/accounts/urls.py
"""authot:
   data:
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # TemplateView可以不写视图函数
    # url(r'^register/$', TemplateView.as_view(template_name="accounts/register.html"), name="register"),
    # 注册
    url(r'^register/$', views.Register.as_view(), name='register'),
    # 登录
    url(r'login/$', views.Login.as_view(), name="login"),
    # 退出
    url(r'logout/$', views.logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.test, name="password_forget"),
    # 重置密码
    url(r'password/reset/token/$',views.test, name="password_reset"),
]

question_repo/apps/apis/urls.py
"""authot:
   data:
"""
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 获取手机验证码
    url(r'^get_mobile_captcha/$', views.get_mobile_captcha, name='get_mobile_captcha'),
    url(r'^get_login_captcha/$', views.get_login_captcha, name='get_captcha'),
    url(r'^check_login_captcha/$', views.check_login_captcha, name='check_captcha'),

    ]

question_repo/apps/repo/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='repo'

urlpatterns = [
    url(r'^$', views.index,name='index')
]

question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

# app_name='learning_logs'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logtest/$', views.logtest, name="logtest"),
    url(r'^index/',include('apps.repo.urls',namespace='index')),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),


]

question_repo/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
# 继承自AbstractUser

class User(AbstractUser):
    realname = models.CharField(max_length=8, verbose_name="真实姓名")
    mobile = models.CharField(max_length=11, verbose_name="手机号")
    qq = models.CharField(max_length=11, verbose_name="QQ号")
    avator_sor = models.ImageField(upload_to="avator/%Y%m%d/", default="avator/default.jpg", verbose_name="头像")

question_repo/apps/accounts/forms.py
"""authot:
   data:
"""

from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2",
        widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")



# 用户登陆
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
        widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
        widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print('hahaha')
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/apps/accounts/views.py
from django.shortcuts import render, redirect, reverse,HttpResponse
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.views.generic import View
import logging
from .forms import LoginForm,RegisterForm
from .models import User

# Create your views here.

logger = logging.getLogger('account')

class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "accounts/register.html", {"form":form})


    # Ajax提交表单
    def post(self, request):
          from django.core.cache import cache
          ret = {"status":400, "msg":"调用方式错误"}
          if request.is_ajax():
              form = RegisterForm(request.POST)
              if form.is_valid():
                  username = form.cleaned_data["username"]
                  password = form.cleaned_data["password"]
                  mobile = form.cleaned_data["mobile"]
                  mobile_captcha = form.cleaned_data["mobile_captcha"]
                  mobile_captcha_reids = cache.get(mobile)
                  if mobile_captcha == mobile_captcha_reids:
                      user = User.objects.create(username=username, password=make_password(password))
                      user.save()
                      ret['status'] = 200
                      ret['msg'] = "注册成功"
                      logger.debug(f"新用户{user}注册成功！")
                      user = auth.authenticate(username=username, password=password)
                      if user is not None and user.is_active:
                          auth.login(request, user)
                          logger.debug(f"新用户{user}登录成功")
                      else:
                          logger.error(f"新用户{user}登录失败")
                  else:
                      # 验证码错误
                      ret['status'] = 401
                      ret['msg'] = "验证码错误或过期"
              else:
                  ret['status'] = 402
                  ret['msg'] = form.errors
          logger.debug(f"用户注册结果：{ret}")
          return JsonResponse(ret)


class Login(View):
    # 当加载Login页面时
    def get(self, request):
        # 如果已登录，则直接跳转到index页面
        # request.user 表示的是当前登录的用户对象,没有登录 `匿名用户`
        if request.user.is_authenticated:
            return redirect(reverse('repo:index'))
        form = LoginForm()
        # 设置下一跳转地址
        request.session["next"] =  request.GET.get('next',reverse('repo:index'))
        return render(request, "login.html", {"form":form})

        # Form表单直接提交
    def post(self, request):
        # 表单数据绑定
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            captcha = form.cleaned_data["captcha"]
            session_captcha_code = request.session.get("captcha_code", "")
            logger.debug(f"登录提交验证码:{captcha}-{session_captcha_code}")
            # 验证码一致
            if captcha.lower() == session_captcha_code.lower():
                user, flag = form.check_password()
                # user = auth.authenticate(username=username, password=password)
                if user is not None and user.is_active:
                    auth.login(request, user)
                    logger.info(f"{user.username}登录成功")
                    # 跳转到next
                    return redirect(request.session.get("next", '/'))
                msg = "用户名或密码错误"
                logger.error(f"{username}登录失败, 用户名或密码错误")
            else:
                msg = "验证码错误"
                logger.error(f"{username}登录失败, 验证码错误")
        else:
            msg = "表单数据不完整"
            logger.error(msg)
        return render(request, "login.html", {"form": form, "msg": msg})

    # # Form表单直接提交
    # def post(self, request):
    #     # 表单数据绑定
    #     form = LoginForm(request.POST)
    #     if form.is_valid():
    #         username = form.cleaned_data["username"]
    #         user, flag = form.check_password()
    #         # user = auth.authenticate(username=username, password=password)
    #         if user is not None and user.is_active:
    #             auth.login(request, user)
    #             logger.info(f"{user.username}登录成功")
    #             # 跳转到next
    #             return redirect(request.session.get("next",'/'))
    #         msg = "用户名或密码错误"
    #         logger.error(f"{username}登录失败, 用户名或密码错误")
    #     else:
    #         msg = "表单数据不完整"
    #         logger.error(form.errors)
    #         logger.error(msg)
    #     return render(request, "login.html", {"form": form, "msg":msg})

def logout(request):
    auth.logout(request)
    return redirect(reverse('accounts:login'))

def test(request):
    return HttpResponse("帐户视图")

question_repo/apps/accounts/templates/accounts/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户注册-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
<body class="login-body">
    <div class="container">
        <form class="form-signin" id="register_form">
          {% csrf_token %}
          <h2 class="form-signin-heading">用户注册</h2>
          <div class="login-wrap">
              {{ form.username }}
              {{ form.password }}
              {{ form.password2 }}
              {{ form.mobile }}
              {{ form.mobile_captcha }}
              {# 给发送短信按钮添加动作 #}
              <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
              <button class="btn btn-lg btn-login btn-block" type="button" id="register_btn">注册</button>
              <label class="checkbox">
                  <span class="pull-right"> 已有帐号， <a href="{% url 'accounts:login' %}"> 请登录 </a></span>
              </label>
              <div class="alert alert-block alert-danger fade in">
                    <button data-dismiss="alert" class="close close-sm" type="button">
                        <i class="icon-remove"></i>
                    </button>
                    <strong>提醒!</strong> 错误提示信息~~
              </div>
          </div>
        </form>
    </div>

    {# 添加js动作#}
    <script>
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:get_mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
            // 如果秒数还是大于0，则表示倒计时还没结束
            if(second>=0){
                // 获取默认按钮上的文字
                if(typeof buttonDefaultValue === 'undefined' ){
                    buttonDefaultValue =  obj.defaultValue;
                }
                // 按钮置为不可点击状态
                obj.disabled = true;
                // 按钮里的内容呈现倒计时状态
                obj.value = buttonDefaultValue+'('+second+')';
                // 时间减一
                second--;
                // 一秒后重复执行
                setTimeout(function(){countDown(obj,second);},1000);
                // 否则，按钮重置为初始状态
            }
            else{
                // 按钮置未可点击状态
                obj.disabled = false;
                // 按钮里的内容恢复初始状态
                obj.value = buttonDefaultValue;
            }
        }
        $("#register_btn").click(function () {
            // some_check
            $.ajax({
                url: "{% url 'accounts:register' %}",
                type: "POST",
                dataType: "json",
                data: $("#register_form").serialize(), // {"username":'cali'}
                success: function (data) {
                    if(data.status == 200 ){
                        window.location.href='{% url 'repo:index' %}';
                    }
                    else{
                        msg = "新错误类型";
                        if(data.status == 400 || data.status == 401){
                            msg = data.msg
                        }
                        else{
                            // 402 => form.errors
                            for(var i in data.msg){
                                msg = i+data.msg[i];
                                break
                            }
                        }
                        $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                            //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: msg
                        });
                    }
                },
                // 解决csrftoken
                beforeSend: function(xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                }
            });
        });
    </script>
</body>
</html>