question_repo/apps/accounts/urls.py
"""authot:
   data:
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # TemplateView可以不写视图函数
    # url(r'^register/$', TemplateView.as_view(template_name="accounts/register.html"), name="register"),
    # 注册
    url(r'^register/$', views.Register.as_view(), name='register'),
    # 登录
    url(r'login/$', views.Login.as_view(), name="login"),
    # 退出
    url(r'logout/$', views.logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.test, name="password_forget"),
    # 重置密码
    url(r'password/reset/token/$',views.test, name="password_reset"),
]

question_repo/apps/apis/urls.py
"""authot:
   data:
"""
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 获取手机验证码
    url(r'^get_mobile_captcha/$', views.get_mobile_captcha, name='get_mobile_captcha'),
    url(r'^get_login_captcha/$', views.get_login_captcha, name='get_captcha'),
    url(r'^check_login_captcha/$', views.check_login_captcha, name='check_captcha'),

    ]

question_repo/apps/repo/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name='repo'

urlpatterns = [
    url(r'^$', views.index,name='index')
]

question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

# app_name='learning_logs'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logtest/$', views.logtest, name="logtest"),
    url(r'^index/',include('apps.repo.urls',namespace='index')),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),


]

question_repo/apps/accounts/forms.py
"""authot:
   data:
"""

from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2",
        widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")



# 用户登陆
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
        widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
        widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print('hahaha')
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="overflow: hidden;" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/img/favicon.html">
    <title>{% block title %}BASE{% endblock %}-题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    {% block load_css %}
    {% endblock %}
    <style>
      body{
          font-size: 14px; !important;
      }
    </style>
</head>
<body>
    <div class="container">
        <section id="container" class="">
          <!--header start-->
          <header class="header white-bg">
              <!--logo start-->
              <a href="#" class="logo">三创<span>题库</span></a>
              <!--logo end-->
              <div class="top-nav">
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <ul class="nav navbar-nav">
                    <li class="active">
                      <a class="" href="http://127.0.0.1:8000/">
                          <span> 首页 </span>
                      </a>
                    </li>
                    <li class="">
                        <a class="" href="http://127.0.0.1:8000/question/">
                      <span> 校招题 </span>
                    </a>
                    </li>
                  </ul>
                  <ul class="nav pull-right top-menu">
                      <li>
                          <form action="/question/">
                             <input type="text" class="form-control search" placeholder="Search" name="search" id="search">
                          </form>
                      </li>
                      <!-- user login dropdown start-->

                      <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                              <img alt="" src="{% static 'img/1534323246.png' %}" height="30px">

                              <span class="username">admin</span>
                              <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                              <div class="log-arrow-up"></div>
                              <li><a class="" href="http://127.0.0.1:8000/uc/profile/"> 个人资料 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/change_passwd/"> 修改密码 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/answer/"> 我的回答 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/collect/"> 我的收藏 </a></li>
                              <li><a class="" href="#myModal-1" data-toggle="modal"> 贡献题目 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/contribut/"> 我的贡献 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/accounts/logout/"> 退出 </a></li>
                          </ul>
                      </li>

                      <!-- user login dropdown end -->
                  </ul>
              </div>
          </header>
          <!--header end-->
          <!--main content start-->
          <section id="main-content">
              <section class="wrapper">
                <!-- page start-->
                <div class="row">
                    {% block content %}这是BASE页面{% endblock %}
                </div>
                <!-- page end-->
              </section>
          </section>
          <!--main content end-->
          </section>
    </div>
    {% include 'crontribute_modal.html' %}
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}" ></script>
    {% block load_js %}
    {% endblock %}
    <script>
      //owl carousel
      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true
          });
      });
    </script>
</body>
</html>

question_repo/templates/crontribute_modal.html
{# My Modal 模态框 #}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
<div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title">贡献题目</h4>
      </div>
      <div class="modal-body">
          <form class="form-horizontal" role="form" method="post" action="/question/">
              <div class="form-group">
                  <label for="inputQuestionTitle" class="col-lg-2 control-label">标题</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" id="inputQuestionTitle" name="title" placeholder="标题">
                  </div>
              </div>
               <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">分类</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="分类" name="category">
                            <option value="0"> 选择分类 </option>
                                <option value="{{ item.id }}">{{ item.name }}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">内容</label>
                    <div class="col-lg-10">
                        <textarea type="text" class="form-control" id="inputQuestionTitle" name="content" placeholder="内容"></textarea>
                    </div>
                </div>
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      <button type="submit" class="btn btn-default">提交</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>

question_repo/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
{#          <form class="form-signin">#}
{#            <h2 class="form-signin-heading">登录</h2>#}
{#            <div class="login-wrap">#}
{#                <input type="text" name="username" class="form-control" placeholder="用户名" maxlength="150" required="" id="id_username">#}
{#                <input type="password" name="password" class="form-control" placeholder="密 码" maxlength="128" required="" id="id_password">#}
{#                <input type="text" name="captcha" class="captcha" placeholder="验证码"  error_messages="{'invalid': '验证码错误'}" required="" id="id_captcha">#}
{#                <a href="javascript:void(0);"><img id="captcha_img" src="data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAeCAIAAABoq03CAAACcUlEQVR4nO1aQXLCMAxcMX1A4cwM#}
{#    Fz7QQzu8hA8wPKIz/QB/gFM/U9pLf1J+oB4MxrHl2I4dJzDscCAeSZbWliInIWbGBURkXnYAEQHI#}
{#    NHKXyGX2gUhMhnYgAJUidwCB6FKxFbFzNwknEH03sflQM0uISE33qNGV8BSUaF//Ua1Tt56n705J#}
{#    9XJl+rkOKBVYfktaB7KXkd7nBFktUYgI4IvZUlaTIZcOFWd7TuVvpaB68aQmGozrLmTVzNbMudR2#}
{#    HkNpST6wiJHrJqY4mLmDZe1PZY5bXE0mWnS913g6GGfmnm4ewXl9Foodwa3AiGBN9/5uj7jC6o+r#}
{#    61NRv/ncHLfQEP74SA6kFPqqtipCy7bvXqSFdV1y1ZvbhAH50tNEYaijmY4ofGAJmmgR0X1V0Bhw#}
{#    rsUGoXZ11mvADMuyFrS8qt9mWA7o/1FEi5y2s7xYYLlkRZ2pJNYvZiYSik8KZHf0YGbrEq/uleR0#}
{#    xPnNwCuwbyrK96jjkV1HfK4B8o+ZPz+9KoPDezLsvHQXXQbegB+OSOTUgp66O5XK8zNOpzTFgphA#}
{#    uFNfbywugha1GPN3sEabKyou7molaqUWFgA9shyzLycwCIVBkw/xjJvY76/UrNcNa+2KX1+uA+cd#}
{#    fTgAwN9fVEfY6yPoGDbkProDlU6HoMdBhO32OjKbCerbrWjTNxcAbDYAMJ1eqRex2xVoPPLPvWN5#}
{#    xmiV6d9fvLw0RkR5Ey2SzEM+Tjq7MRKibxrucxW3I5RfztZ/95wzo6Vb33m30rrbV3452/c2d7lw#}
{#    Z4zn6yaS8lE6gCofWD2IroSxf6nUjhv6jum2ic5Px2pL9Q+TVYba1BF5qAAAAABJRU5ErkJggg==#}
{#    " ></a>#}
{#                <div class="user-reg">#}
{#                    <a href="#"> 用户注册</a>#}
{#                    <span class="pull-right"> <a href=""> 忘记密码?</a></span>#}
{#                </div>#}
{#                <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>#}
{#            </div>#}
{#          </form>#}
            <form class="form-signin" action="{% url "accounts:login" %}" method="post">
                {% csrf_token %}
                <h2 class="form-signin-heading">登录</h2>
                <div class="login-wrap">
                    {{ form.username}}
                    {{ form.password}}
                    {{ form.captcha}}
                    <a href="javascript:void(0);"><img id="captcha_img" src="#" /></a>
                    <label class="checkbox">
                        <input type="checkbox" value="remember-me"> 记住密码
                        <span class="pull-right"> <a href="#"> 忘记密码?</a></span>
                    </label>
                    <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
                    <p class="msg"></p>
                    {% if msg %}
                    <div class="alert alert-block alert-danger fade in">
                          <button data-dismiss="alert" class="close close-sm" type="button">
                              <i class="icon-remove"></i>
                          </button>
                          <strong>提醒!</strong> {{ msg }}
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>

        <script>
        get_captcha_img();
        $("#captcha_img").click(get_captcha_img);

        function get_captcha_img() {
            $.ajax({
                url: '{% url 'apis:get_captcha' %}',
                type: 'GET',
                dataType: 'text',
                success: function (data) {
                    $('#captcha_img').attr('src', data);
                }
            });
        }
        </script>
        <script>
        // 这里在form中定义了，如果没定义可以用jquery添加事件
        // $("#id_captcha").blur(check_captcha);

        // 当失去焦点时检查验证码
        function check_captcha() {
            var captcha_code = $('#id_captcha').val();
            if (captcha_code.length == 0){
                return false
            }
            $.ajax({
                url: '{% url 'apis:check_captcha' %}',
                type: 'GET',
                dataType: 'json',
                data: {"captcha_code": captcha_code},
                success: function (data) {
                    if(data.code == 400){
                         $('.msg').html("验证码错误");
                    }else{
                        $('.msg').html("");
                    }
                }
            });
        };
        </script>
    </body>
</html>

question_repo/templates/register.html
{# 加载提示工具对应的js和css #}
<link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
<script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>

{# 给发送短信按钮添加动作 #}
<input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/></p>

{# 添加js动作#}
<script>
    {# 发送短信验证码 #}
    function sendmessage(obj,second){
        var telRegex = /(13|14|15|17|18)\d{9}/;
        if(telRegex.test($.trim($("#id_mobile").val()))){
		    $.ajax({
                url: "{% url 'apis:get_mobile_captcha' %}",
                type: "GET",
                dataType: "json",
                data: {"mobile": $("#id_mobile").val()},
                success: function (data) {
                     $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '提交结果',
                        // (string | mandatory) the text inside the notification
                      //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                        text: data.msg
                    });
                }
            });
			countDown(obj,second)
        } else{
            $.gritter.add({
                // (string | mandatory) the heading of the notification
                title: '提交结果',
                // (string | mandatory) the text inside the notification
                //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                text: '手机号有误'
            });
        }
    }

    {# 重新发送倒计时 #}
	function countDown(obj,second){
    // 如果秒数还是大于0，则表示倒计时还没结束
     if(second>=0){
          // 获取默认按钮上的文字
          if(typeof buttonDefaultValue === 'undefined' ){
            buttonDefaultValue =  obj.defaultValue;
        }
        // 按钮置为不可点击状态
        obj.disabled = true;
        // 按钮里的内容呈现倒计时状态
        obj.value = buttonDefaultValue+'('+second+')';
        // 时间减一
        second--;
        // 一秒后重复执行
        setTimeout(function(){countDown(obj,second);},1000);
        // 否则，按钮重置为初始状态
        }else{
        // 按钮置未可点击状态
        obj.disabled = false;
        // 按钮里的内容恢复初始状态
        obj.value = buttonDefaultValue;
       }
    }
</script>
<script>
    $("#register_btn").click(function () {
        // some_check
        $.ajax({
            url: "{% url 'accounts:register' %}",
            type: "POST",
            dataType: "json",
            data: $("#register_form").serialize(),
            success: function (data) {
                if(data.status == 200 ){
                    window.location.href='{% url 'repo:index' %}';
                }else{
                    msg = "新错误类型"
                    if(data.status == 400 || data.status == 401){
                        msg = data.msg
                    }else{
                        for(var i in data.msg){
                            msg = i+data.msg[i]
                            break
                        }
                    }
                     $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '提交结果',
                        // (string | mandatory) the text inside the notification
                        //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                        text: msg
                    });
                 }
            },
            // 解决csrftoken
            beforeSend: function(xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            }
        });
    });
</script>